---
- name: Update host
  become: true
  dnf:
    name: "*"
    state: latest
  notify:
    - Restart system

- name: Enable EPEL Repository on CentOS 8
  become: true
  dnf:
    name: epel-release
    state: latest
