---
- name: Add Docker dnf repository
  become: true
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Add packages
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - dnf-plugins-core
    - yum-utils
    - containerd
    - docker-ce
    - docker-ce-cli

- name: Start and Enable Docker service
  become: true
  service:
    name: docker
    state: started
    enabled: true
    daemon_reexec: true
