---
- name: Install nfs
  become: true
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - nfs-utils
    - rpcbind

- name: Start and enable service nfs nfs-server
  become: true
  service:
    name: nfs-server
    state: started
    enabled: true

- name: Start and enable service rpc-bind
  become: true
  service:
    name: rpcbind
    state: started
    enabled: true

- name: Create export folder
  become: true
  file:
    path: /cinder_export
    state: directory
    mode: '0777'
    owner: vagrant
    group: vagrant

- name: Define export file
  become: true
  lineinfile:
    path: /etc/exports
    create: true
    line: "/cinder_export 172.28.128.0/24(rw,sync,no_subtree_check,no_root_squash)"
    owner: root
    group: root
    mode: '0644'
  notify: Reload nfs server
