---
- name: Install public key for ssh connection
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', './id_rsa.pub') }}"

- name: Copy private ssh key for ssh connection
  copy:
    src: ./id_rsa
    dest: /home/vagrant/.ssh/id_rsa
    mode: '0600'
    owner: vagrant
    group: vagrant

- name: Copy public ssh key for ssh connection
  copy:
    src: ./id_rsa.pub
    dest: /home/vagrant/.ssh/id_rsa.pub
    mode: '0600'
    owner: vagrant
    group: vagrant

- name: Remove dupplicate hostname in hosts file
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: '^127(.+)$'
    state: absent

- name: Install growpart
  become: true
  dnf:
    name: cloud-utils-growpart
    state: latest

- name: partition info
  become: true
  parted:
    device: "{{dev}}"
    number: "{{part}}"
  register: partinfo

- name: calculate gap after partition
  set_fact:
    gap_kb: "{{partinfo.disk.size - partinfo.partitions[vars.part-1].end}}"

- name: Extend partition
  become: true
  command: "growpart {{ dev }} {{ part }}"
  when: max_gap_kb < gap_kb|int

- name: grow filesystem until maximum block size
  become: true
  filesystem:
    fstype: xfs
    dev: "{{ dev }}{{ part }}"
    resizefs: yes
