---
- name: Install packages before terraform
  package: 
    name: "{{ item }}"
    state: latest
  loop:
    - wget
    - unzip

- name: terraform install
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.14.0/terraform_0.14.0_linux_amd64.zip
    dest: /usr/bin
    remote_src: True
