---
- name: enable powertools
  ini_file:
    path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
    section: powertools
    option: enabled
    value: "1"
    mode: "0644"

- name: Install Openstack client
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ openstack_client_packages }}"
